### ISSUE TITLE
Adding levels

### ISSUE THREAD

**Issue by kittylegitcheck** [Mysttt/Discord-Levels-Bot#4]
Hi, i wanted to add levels to my acc but i do not know how

**Comment by Mysttt** [comment]
Hey,

At the current moment the only way of doing this is by changing your XP through the database. Once you've done that, check your level by doing !rank (replace ! with your prefix) and then set whatever level you are in the database. At any moment you want to reset yourself, use the reset command. I will work on a add rank/xp command.

Hope this helps :)

**Comment by kittylegitcheck** [comment]
Okay tysm!
