### ISSUE TITLE
I tried to add via database

### ISSUE THREAD

**Issue by kittylegitcheck** [Mysttt/Discord-Levels-Bot#5]
![image](https://user-images.githubusercontent.com/79789524/110748386-edda7680-823f-11eb-8d23-0d8949c4e785.png)
I added xp, than bot no work i redo the stuff i done and still did not fix
![image](https://user-images.githubusercontent.com/79789524/110748983-c33ced80-8240-11eb-9c32-4ca22ea2c0f2.png)

**Comment by Mysttt** [comment]
Hey,

I'm not sure what has happened as this project does not use Sqlite, rather it uses mongoDB. Also, looking into your error I'm noticing you have .js files as well as well as node modules. Below you'll see a screenshot of what your project should look like in file explorer. Make sure python 3.9 is installed. If it does not look similar, reinstall from the repo page and fill in all the details again. Once you've done that I will further help to add XP to a certain user.

![screenshot](https://user-images.githubusercontent.com/63556081/110870746-00e35a00-82c5-11eb-91c6-5c0a7b8e5fb3.PNG)

**Comment by kittylegitcheck** [comment]
yeah it works now. TY

**Comment by Mysttt** [comment]
Glad to hear :)
