### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by technomaniak** [Mysttt/Discord-Levels-Bot#7]
**Describe the bug**
starting bot and not working 

**To Reproduce**
add the bot to replit.com
install all reqs
do: python3 main.py

**Expected behaviour**
bot is supposed to work

**Screenshots**
![image](https://user-images.githubusercontent.com/49454508/112308028-f0a68400-8ca1-11eb-89b1-58648cc96dbe.png)

**Comment by Mysttt** [comment]
You seem to have set your database up wrong. Looking at the error, you’ll see it stated the database name cannot include ‘ ‘. If you need help setting up the database, i’ll happily help

**Comment by technomaniak** [comment]
How do i setup the database than? I am using replit.com for the bot.

**Comment by Mysttt** [comment]
Join my discord server. It’ll be a lot easier there for me to help you, and i’ll see it a lot faster

**Comment by technomaniak** [comment]
okay

**Comment by Mysttt** [comment]
Hey sorry I didn't see your edit. Here's the link: https://discord.gg/HwJhy88aGm

**Comment by technomaniak** [comment]
i am in

**Comment by Z1R343L** [comment]
just in case u didn't got it running yet;
have u correctly filled in ur mongodb infos in levelsys.py?
